# この文書について {.unnumbered}

データサイエンス、AI（Artificial Intelligence 人工知能）関連で考えたこと、および調べたことを、メモがわりに、書いていこうと思っている。いずれは、データサイエンスと言える内容を発信できると良いと思っている。

まとまった内容を書く予定はいまのところない。

現在は、データサイエンスと言える内容を、書くだけの力がないだけではなく、以下のプロジェクトが進行中で、そのための、下調べのメモを中心に書いていく。

## データサイエンスをはじめましょう

基本的に、自習型の、学習コンテンツで、大学などで、教えるためにも、学習者に参考にしてもらうための、内容を書いていきたい。

断片的なものは、多くあるが、まとまったものは、英文では豊富にあるにもかかわらず、日本語では、十分ではないと感じているからである。

むろん、教科書と言われるような、標準的なものを目指しているわけではない。自分が学んでいて、たいせつだと考えることを、順を追って、書いていく予定である。

以下を土台としている。

-   大学院一般向けに、さまざまな背景の学生に何年か教えてきた内容

    -   [Data Analysis for Researchers 2022](https://icu-hsuzuki.github.io/da4r2022/)

    -   [Data Analysis for Researchers 2021](https://icu-hsuzuki.github.io/da4r2021/)

-   中級マクロを受講している学生向けの、特別講師として、教えた内容に、後日加筆したもの

    -   [Rではじめるデータ・サイエンス](https://ds-sl.github.io/intro2r/intro2rj.nb.html)

-   経済学の大学院生むけの、特別講師として教えた内容

    -   [Introduction to R - A Short Course](https://ds-sl.github.io/intro2r/intro2r.nb.html)

## データサイエンスを教えませんか

データサイエンス教育に関する素材を集めたものとしてスタートしたが、基本的には、データサイエンスにあまり馴染みがないが、学びながら、教えていきたい方向けのコンテンツを目指している。

データサイエンス教育は喫緊の課題であるが、情報科学の一部の教員または技術者以外は、特に日本では、データサイエンスに馴染みがない。しかし、大学（または、高等専門学校や高校など）で全学的に、データサイエンス教育を推進しようとすると、多くの教員の関与が必要である。

社会科学系を中心として、大学教員の中には、データ分析を使う分野は多い。経済学、社会学、心理学、言語学などなど。そのような教員にも、積極的にに、データサイエンス教育に加わっていただくための支援を目的として、書いていこうと思っている。

なお、この背景にある考え方は、以下の講演などで、語っている。

-   [日本でのデータサイエンス教育の課題にどう向き合うか](https://ds-sl.github.io/intro2r/rims2023.nb.html)

    -   [スライド](https://ds-sl.github.io/intro2r/rims2023.html)・[ビデオ](https://youtu.be/dT_T0rPCvY4)（2023年3月9日の数理科学研究所での午前の講演）

-   [生涯学び続ける基盤を構築するデータサイエンス・コースの開発](https://ds-sl.github.io/intro2r/rims2023p.nb.html)

    -   [スライド](https://ds-sl.github.io/intro2r/rims2023p.html)・[ビデオ](https://youtu.be/8PY9wlzFQz0)（2023年3月9日の数理科学研究所での午後の講演前半・後半は「[Rではじめるデータ・サイエンス](https://ds-sl.github.io/intro2r/intro2rj.nb.html")」

-   教養としてのデータサイエンス教育～MOOCsの活用を視野に入れて～　[日本数学会教育委員会主催教育シンポジウム](https://www.mathsoc.jp/overview/committee/education/sympo/2019sep.html)：文理共通して行う数理・データサイエンス教育における講演　時：2019年9月17日　於：金沢大学角間キャンパス

    -   [スライド](https://icu-hsuzuki.github.io/datascience/ed/msj2019.pdf)・[音声付き画面収録ビデオ](https://drive.google.com/file/d/1swnSefj7Wxjvs4MGmz9IuKRjwAMnjrlJ/view?usp=sharing)
